### ISSUE TITLE
I don't wanna to be blocked on Instagram

### ISSUE THREAD

**Issue by naziko2411** [aahouzi/Instagram-Scraper-2021#1]
Hey! I really like your project! XPath Selenium is very useful for picking dates for me! But does it blocks my Instagram account after I logged into this?

**Comment by ghost** [comment]
Sometimes Instagram blocks access for ur Selenium code, if u tried to scrap data many times in a row. In case this happens, u are redirected to a logging page, and in my code u connect with a random account I created just to continue scrapping. To answer ur question, u can't do anything about getting blocked since it's more related to Instagram. However, most of the times it works pretty well for me without getting blocked. For example, I just runned the code three times in a row now without getting blocked. I wish I answered ur questions clearly enough.

**Comment by naziko2411** [comment]
I thought that Xpath selenium was helpful for any content.

**Comment by ghost** [comment]
Yeah, but depending on the website u are scraping. If u are scraping Stackoverflow for example, u won't face these problems of getting blocked. Good luck!
