### ISSUE TITLE
Can you write a little tutorial on how to use/setup your script Please? 

### ISSUE THREAD

**Issue by redyellowRain** [aahouzi/Instagram-Scraper-2021#4]
I am Trying to scrape for all Images of a particular hashtag. For example "#beach". Will your scraper collect all the images or only the urls of images? If it only collects the Urls of images do you know of another utility that will get the actual images based on those Urls? Please write instructions on how to use and set up your code. I'm not a programmer but need this for a project and would love to use it. Thank you for your hard work!

**Comment by ghost** [comment]
Hi! Yes, it only collects urls because my code is meant for scraping images, and not downloading them. If u want to download an image from a url just use requests.get(<url>) in Python, u can google it out. Regarding ur question about hashtags, the version that supports hashtag scraping is still under development since I didn't get much time to complete it. Hope I answered ur questions.
